<Project Sdk="Microsoft.NET.Sdk.Web">
      <ItemGroup>
        <ProjectReference Include="../BookKnowledge.ContentSearch.Application/BookKnowledge.ContentSearch.Application.csproj" />
        <ProjectReference Include="../BookKnowledge.ContentSearch.Infrastructure/BookKnowledge.ContentSearch.Infrastructure.csproj" />
        <ProjectReference Include="../../ServiceDefaults/BookKnowledge.ServiceDefaults/BookKnowledge.ServiceDefaults.csproj" />
      </ItemGroup>
      <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
      </ItemGroup>
    </Project>