<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup><ProjectReference Include="../BookKnowledge.ContentSearch.Application/BookKnowledge.ContentSearch.Application.csproj" /></ItemGroup>
  <ItemGroup><ProjectReference Include="../../BuildingBlocks/BookKnowledge.BuildingBlocks/BookKnowledge.BuildingBlocks.csproj" /></ItemGroup>
</Project>
