<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup><ProjectReference Include="../BookKnowledge.ContentSearch.Domain/BookKnowledge.ContentSearch.Domain.csproj" /></ItemGroup>
  <ItemGroup><ProjectReference Include="../../BuildingBlocks/BookKnowledge.BuildingBlocks/BookKnowledge.BuildingBlocks.csproj" /></ItemGroup>
</Project>
